GROUPS = ['traxx', 'xenot', 'viviz', 'tribe', 'stayc', 'romeo', 'justb', 'izone', 'creal', 'blady', 'elris', 'rania', 'trcng', 'twice', 'elast', 'loona', 'onewe', 'oneus', 'ateez', 'aespa', 'missa', 'gidle', 'apink', 'beast', 'astro', 'nuest', 'ukiss', 'mblaq', 'april', 'spica', 'speed']

GROUP_NAME = ['TraxX', 'Xeno-T', 'Viviz', 'Tri.be', 'Stayc', 'Romeo', 'Just B', 'IZ*ONE', 'C-Real', 'Blady', 'Elris', 'Rania', 'TRCNG', 'Twice', 'E\'last', 'Loona', 'Onewe', 'Oneus', 'ATEEZ', 'Aespa', 'Miss A', '(G)I-DLE', 'APink', 'Beast', 'Astro', 'Nu\'est', 'U-Kiss', 'MBLAQ', 'April', 'Spica', 'Speed']

IDOLS = ['leedo', 'jiwoo', 'jinho', 'intak', 'etion', 'wyatt', 'naeun', 'jiwon', 'solji', 'eunji', 'jseph', 'fatou', 'minzy', 'sunmi', 'serim', 'allen', 'bomin', 'crush', 'jamie', 'tablo', 'wonho', 'tzuyu', 'jisoo', 'yanan', 'elkie', 'yujin', 'sanha', 'nancy', 'dawon', 'lucas', 'yunho', 'mingi', 'jacob', 'hyuna', 'hwasa', 'solar', 'minho', 'felix', 'jihyo', 'eunha', 'irene', 'wendy', 'jimin', 'jhope', 'keeho' , 'sehun', 'bobby', 'jessi', 'hoshi', 'taeil', 'rocky', 'yerin', 'somin', 'kevin', 'woozi', 'woodz']

IDOL_FROM = ['Oneus', 'KARD', 'Pentagon', 'P1Harmony', 'ONF', 'ONF', 'Apink', 'Cherry Bullet', 'EXID', 'APink', 'KARD', 'Black Swan', '2NE1', 'soloist', 'Cravity', 'Cravity', 'Golden Child', 'soloist', 'soloist', 'Epik High', 'soloist', 'Twice', 'Blackpink', 'Pentagon', 'CLC', 'GFriend', 'Astro', 'Momoland', 'SF9', 'NCT', 'ATEEZ', 'ATEEZ', 'The Boyz', 'soloist', 'Mamamoo', 'Mamamoo', 'SHINee', 'Stray Kids', 'Twice', 'Gfriend', 'Red Velvet', 'Red Velvet', 'BTS', 'BTS', 'P1Harmony', 'EXO', 'iKon', 'soloist', 'Seventeen', 'NCT', 'Astro', 'Gfriend', 'KARD', 'The Boyz', 'Seventeen', 'soloist']

SONGS = ['venom', 'queen', 'shock', 'loved', 'swear', 'skinz', 'angel', 'elvis', 'alone', 'rumor', 'chain', 'punch', 'seoul', 'flash', 'petal', 'genie', 'devil', 'flame', 'power', 'cider', 'movie', 'loser', 'tempo', 'lotto', 'shine', 'crazy', 'first', 'fancy', 'fever', 'adios', 'karma', 'growl', 'crown', 'miroh', 'apple', 'siren', 'daisy', 'error', 'maria', 'likey', 'money']

SONG_BY = ['Stray Kids', 'History', 'Beast', 'Highlight', 'E\'Last', 'OnlyOneOf', 'OnlyOneOf', 'AOA', 'Sistar', 'KARD', 'NCT 127', 'NCT 127', 'Ghost9', 'X1', 'APink', 'Girls Generation', 'CLC', 'Cravity', 'EXO/B.A.P', 'Yezi', 'BTOB', 'Big Bang', 'EXO', 'EXO', 'Pentagon', '4Minute', 'Everglow', 'Twice', 'Enhypen', 'Everglow', 'Kingdom', 'EXO', 'TXT', 'Stray Kids', 'GFriend', 'P1Harmony/Sunmi', 'Pentagon', 'VIXX', 'Hwasa', 'Twice', 'Lisa']
